import { useState } from 'react';
import { createPortal } from 'react-dom';
import './PortalBasic.css'

export default function PortalBasic() {
  const [show, setShow] = useState(false);
  const handleDialog = () => setShow(s => !s);

  return (
    <form>
      <button type="button" onClick={handleDialog} disabled={show}>
        Show Dialog
      </button>
      {show && createPortal(
        <div className="dialog">
          <p>Generated by Portal</p>
          <button type="button" onClick={handleDialog}>
            Close
          </button>
        </div>,
        document.getElementById('dialog')
      )}
    </form>
  );
}

